### ISSUE TITLE
The restaurants count is different before and after clicking reset/filter button (No filters applied initially as well)

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/dine-safe-ly#169]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The restaurant count increases to 6855 from 3674 if I just open the restaurants page and click reset or filter button

## Expected Behavior

The page should give all the restaurants without any filters. And the count should not change.

## Current Behavior

The count increases.

## Steps to Reproduce

1. Navigate to restaurants page.
2. Without applying any filter, check the count (3674)
![image](https://user-images.githubusercontent.com/55005259/100261337-3cbe0380-2f10-11eb-9091-a9d4c69c712f.png)

3. Click the reset or filter button. The count changes to 6855
![image](https://user-images.githubusercontent.com/55005259/100261434-56f7e180-2f10-11eb-99fb-a17cc0d3c1ae.png)

**Comment by Chuanqi927** [comment]
Hello, thanks for pointing this out. We have noticed this. The reason is that we tend to not display restaurants that do not have any information on Yelp becuase we will not be able to provide any useful information for those. For the implementaion of search and filter we are using the whole database so you can tell the difference.

**Comment by gauravag2207** [comment]
Hi @Edward0o0 ,
I think it should be consistent. Either it should show all or it should show only yelp ones.

Thanks,
Gaurav
